services:
  redis:
    image: "redis:8-alpine"
    container_name: pocket-url-shared-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - "redis-data:/data"
    command: redis-server --appendonly yes
    networks:
      - pocket-url-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redis/redisinsight:2.70
    container_name: pocket-url-shared-redis-insight
    ports:
      - "${REDIS_INSIGHT_PORT:-5540}:5540"
    networks:
      - pocket-url-network
    volumes:
      - redis-insight-data:/data
    restart: unless-stopped
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pocket-url-shared-rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_DEFAULT_USER:-admin}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_DEFAULT_PASS:-admin}'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - pocket-url-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  pocket-url-network:
    name: pocket-url-network
    external: true

volumes:
  redis-data:
  redis-insight-data:
  rabbitmq-data:
