services:
  redirector-node:
    image: redirector-node
    build:
      context: ../../../../.
      dockerfile: infrastructures/docker-compose/apps/redirector-node/docker/Dockerfile
      target: development
    container_name: pocket-url-redirector-node
    ports:
      - '${REDIRECTOR_NODE_PORT:-3000}:3000'
      - '${REDIRECTOR_METRICS_PORT:-9464}:9464'
    environment:
      - SHORTENER_GRPC_URL=pocket-url-shortener-grpc:${SHORTENER_GRPC_PORT:-5001}
      - NODE_OPTIONS="--max-old-space-size=512"
    env_file:
      - ../../../../apps/redirector-node/.env
    volumes:
      - ../../../../apps/redirector-node:/app:cached
    networks:
      - pocket-url-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${REDIRECTOR_NODE_PORT:-3000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pocket-url-network:
    name: pocket-url-network
    external: true