services:
  app:
    image: shortener-api
    build:
      context: ../../../../.
      dockerfile: infrastructures/docker-compose/apps/shortener/docker/frankenphp/Dockerfile
    environment:
      - DB_HOST=mysql
      - XDEBUG_MODE=coverage
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
    ports:
      - '${SHORTENER_API_PORT:-8000}:80'
    volumes:
      - ../../../../apps/shortener:/app
    depends_on:
      - mysql
    networks:
      - shortener-api-network
      - pocket-url-network
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql
      - ../../../../infrastructures/docker-compose/apps/shortener/docker/mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD", "mysqladmin", 'ping', '-p${MYSQL_ROOT_PASSWORD}']
      timeout: 5s
      retries: 3
    networks:
      - shortener-api-network

networks:
  pocket-url-network:
    name: pocket-url-network
    external: true
  shortener-api-network:
    name: shortener-api-network
    driver: bridge

volumes:
  mysql-data:
